# Open data from other papers

In [1]:
import os, sys

import pandas as pd

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

In [2]:
pd.set_option('max_colwidth', 800)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

datasets = os.path.join(notebook_dir, '../data/others/')

## Canonical_IFP_Bank_Dataverse.xlsx - spreadsheet that contains the domains, topics, and question templates delivered throughout the competitions.
- https://dataverse.harvard.edu/file.xhtml?fileId=4105158&version=2.0

In [ ]:
file = os.path.join(datasets, 'paper_hfc/Canonical_IFP_Bank_Dataverse.xlsx')
ifp_df = pd.read_excel(file, engine='openpyxl')
ifp_df.head()

## RCT_daily-forecasts.csv: For each performer forecasting method, this report provides the last forecast for each scoring day (i.e., the last forecast before 2:01pm ET).
- https://dataverse.harvard.edu/file.xhtml?fileId=4105158&version=2.0

In [ ]:
# file = os.path.join(datasets, 'paper_hfc/rct-a-daily-forecasts.csv')
# forecasts_df = pd.read_csv(file)
# forecasts_df

## RCT_prediction-sets.csv: A list of all individual-level forecasts (aka. Prediction sets) created in the system.
- https://dataverse.harvard.edu/file.xhtml?fileId=4105158&version=2.0

In [ ]:
# file = os.path.join(datasets, 'paper_hfc/rct-a-prediction-sets.csv')
# previous_sets_df = pd.read_csv(file)
# previous_sets_df

## RCT_questions-answers.csv: A list of all questions (aka. IFP's), their answers, and associated metadata such as dates and descriptions.
- https://dataverse.harvard.edu/file.xhtml?fileId=4105158&version=2.0

In [ ]:
file = os.path.join(datasets, 'paper_hfc/rct-a-questions-answers.csv')
qa_df = pd.read_csv(file)
# qa_df.head(7)

## IQVS

In [ ]:
file = os.path.join(datasets, 'paper_iqvs/Train/[QVS] Seed_Trends (seq annotation).xlsx')
qvs_df = pd.read_excel(file, engine='openpyxl')
# qvs_df

In [ ]:
file = os.path.join(datasets, 'paper_iqvs/Covid/train/1197_seq.tsv')
seq_1197_df = pd.read_csv(file, sep='\t')
seq_1197_df

In [ ]:
file = os.path.join(datasets, 'paper_iqvs/Covid/train/28207257_seq.tsv')
seq_28207257_df = pd.read_csv(file, sep='\t')
seq_28207257_df

In [6]:
file = os.path.join(datasets, 'paper_iqvs/TradingEconomics/train/2009_seq.tsv')
seq_28207257_df = pd.read_csv(file, sep='\t')
seq_28207257_df

           Sentence #          Word    POS    Tag
0    Sentence: 2009-1       Exports   NOUN  B-Ind
1                 NaN          from    ADP  I-Ind
2                 NaN         China  PROPN  I-Ind
3                 NaN          rose   VERB   B-Tr
4                 NaN           1.1    NUM   I-Tr
5                 NaN       percent   NOUN   I-Tr
6                 NaN          year   NOUN      O
7                 NaN             -  PUNCT      O
8                 NaN            on    ADP      O
9                 NaN             -  PUNCT      O
10                NaN          year   NOUN      O
11                NaN            to    ADP      O
12                NaN           USD  PROPN      O
13                NaN        213.85    NUM      O
14                NaN       billion    NUM      O
15                NaN            in    ADP      O
16                NaN           May  PROPN      O
17                NaN          2019    NUM      O
18                NaN             ,  PUNCT      O
19                NaN    recovering   VERB      O
20                NaN          from    ADP      O
21                NaN             a    DET      O
22                NaN           2.7    NUM   B-Tr
23                NaN       percent   NOUN   I-Tr
24                NaN       decline   NOUN   I-Tr
25                NaN            in    ADP      O
26                NaN           the    DET      O
27                NaN      previous    ADJ      O
28                NaN         month   NOUN      O
29                NaN           and  CCONJ      O
30                NaN       defying   VERB      O
31                NaN        market   NOUN  B-Ind
32                NaN  expectations   NOUN  I-Ind
33                NaN            of    ADP      O
34                NaN             a    DET      O
35                NaN           3.8    NUM   B-Tr
36                NaN       percent   NOUN   I-Tr
37                NaN          fall   NOUN   I-Tr
38                NaN             .  PUNCT      O
39   Sentence: 2009-2           The    DET      O
40                NaN       rebound   NOUN   B-Tr
41                NaN            in    ADP      O
42                NaN      overseas    ADJ  B-Ind
43                NaN         sales   NOUN  I-Ind
44                NaN          came   VERB      O
45                NaN            in   PART      O
46                NaN          amid    ADP      O
47                NaN       efforts   NOUN      O
48                NaN          from    ADP      O
49                NaN     companies   NOUN      O
50                NaN            to   PART      O
51                NaN          rush   VERB      O
52                NaN           out   PART      O
53                NaN     shipments   NOUN      O
54                NaN            to   PART      O
55                NaN         avoid   VERB      O
56                NaN        higher    ADJ      O
57                NaN            US  PROPN      O
58                NaN       tariffs   NOUN      O
59                NaN          that    ADP      O
60                NaN            US  PROPN      O
61                NaN     President  PROPN      O
62                NaN        Donald  PROPN      O
63                NaN         Trump  PROPN      O
64                NaN            is   VERB      O
65                NaN   threatening   VERB      O
66                NaN            to   PART      O
67                NaN        impose   VERB      O
68                NaN            in    ADP      O
69                NaN             a    DET      O
70                NaN       rapidly    ADV      O
71                NaN    escalating   VERB      O
72                NaN         trade   NOUN      O
73                NaN      conflict   NOUN      O
74                NaN             .  PUNCT      O
75   Sentence: 2009-3         Sales   NOUN  B-Ind
76                NaN          rose   VERB   B-Tr
77                NaN           for    ADP      O
78                NaN     unwrought    ADJ      O
79                NaN     aluminium   NOUN      O
80                NaN           and  CCONJ      O
81                NaN     aluminium   NOUN      O
82                NaN      products   NOUN      O
83                NaN             (  PUNCT      O
84                NaN          10.5    NUM      O
85                NaN       percent   NOUN      O
86                NaN             )  PUNCT      O
87                NaN             ;  PUNCT      O
88                NaN          coke   NOUN      O
89                NaN             &  CCONJ      O
90                NaN          semi    ADJ      O
91                NaN             -   NOUN      O
92                NaN          coke   NOUN      O
93                NaN             (  PUNCT      O
94                NaN           4.8    NUM      O
95                NaN       percent   NOUN      O
96                NaN             )  PUNCT      O
97                NaN             ;  PUNCT      O
98                NaN           and  CCONJ      O
99                NaN          rice   NOUN      O
100               NaN             (  PUNCT      O
101               NaN         236.3    NUM      O
102               NaN       percent   NOUN      O
103               NaN             )  PUNCT      O
104               NaN             .  PUNCT      O
105  Sentence: 2009-4            In    ADP      O
106               NaN      contrast   NOUN      O
107               NaN             ,  PUNCT      O
108               NaN       exports   NOUN  B-Ind
109               NaN            of    ADP  I-Ind
110               NaN         steel   NOUN  I-Ind
111               NaN      products   NOUN  I-Ind
112               NaN       dropped   VERB   B-Tr
113               NaN          16.6    NUM   I-Tr
114               NaN       percent   NOUN   I-Tr
115               NaN             ;  PUNCT   I-Tr
116               NaN         while    ADP      O
117               NaN         those    DET      O
118               NaN            of    ADP      O
119               NaN          coal   NOUN      O
120               NaN      declined   VERB      O
121               NaN          39.6    NUM      O
122               NaN       percent   NOUN      O
123               NaN             .  PUNCT      O
124  Sentence: 2009-5       Exports   NOUN  B-Ind
125               NaN            of    ADP  I-Ind
126               NaN          rare    ADJ  I-Ind
127               NaN        earths   NOUN  I-Ind
128               NaN       slumped   VERB   B-Tr
129               NaN          18.2    NUM   I-Tr
130               NaN       percent   NOUN   I-Tr
131               NaN          from    ADP      O
132               NaN             a    DET      O
133               NaN          year   NOUN      O
134               NaN           ago    ADV      O
135               NaN             .  PUNCT      O
136  Sentence: 2009-6         Among    ADP      O
137               NaN         China  PROPN      O
138               NaN            's   PART      O
139               NaN       largest    ADJ      O
140               NaN         trade   NOUN      O
141               NaN      partners   NOUN      O
142               NaN             ,  PUNCT      O
143               NaN       exports   NOUN  B-Ind
144               NaN          rose   VERB   B-Tr
145               NaN            to    ADP      O
146               NaN           the    DET      O
147               NaN            EU  PROPN      O
148               NaN             (  PUNCT      O
149               NaN           6.1    NUM      O
150               NaN       percent   NOUN      O
151               NaN             )  PUNCT      O
152               NaN             ,  PUNCT      O
153               NaN         ASEAN  PROPN      O
154               NaN             (  PUNCT      O
155               NaN           3.5    NUM      O
156               NaN       percent   NOUN      O
157               NaN             )  PUNCT      O
158               NaN             ,  PUNCT      O
159               NaN        Taiwan  PROPN      O
160               NaN             (  PUNCT      O
161               NaN          12.8    NUM      O
162               NaN       percent   NOUN      O
163               NaN             )  PUNCT      O
164               NaN             ,  PUNCT      O
165               NaN         Japan  PROPN      O
166               NaN             (  PUNCT      O
167               NaN           0.5    NUM      O
168               NaN       percent   NOUN      O
169               NaN             )  PUNCT      O
170               NaN             ,  PUNCT      O
171               NaN         South  PROPN      O
172               NaN         Korea  PROPN      O
173               NaN             (  PUNCT      O
174               NaN           1.8    NUM      O
175               NaN       percent   NOUN      O
176               NaN             )  PUNCT      O
177               NaN           and  CCONJ      O
178               NaN     Australia  PROPN      O
179               NaN             (  PUNCT      O
180               NaN             2    NUM      O
181               NaN       percent   NOUN      O
182               NaN             )  PUNCT      O
183               NaN             .  PUNCT      O
184  Sentence: 2009-7            In    ADP      O
185               NaN      contrast   NOUN      O
186               NaN             ,  PUNCT      O
187               NaN         sales   NOUN  B-Ind
188               NaN            to    ADP  I-Ind
189               NaN           the    DET  I-Ind
190               NaN            US  PROPN  I-Ind
191               NaN          fell   VERB   B-Tr
192               NaN           4.2    NUM   I-Tr
193               NaN       percent   NOUN   I-Tr
194               NaN             .  PUNCT   I-Tr

## MF

In [ ]:
file = os.path.join(datasets, 'paper_mf/paper_mf_repo/data/medical/patient_517.csv')
p517_df = pd.read_csv(file)
p517_df.head(7)

In [4]:
file = os.path.join(datasets, 'paper_mf/paper_mf_repo/data/climate/climate_2014_2023_final.csv')
p517_df = pd.read_csv(file)
p517_df

            date  temp  precip  humidity  windspeed  \
0     2014-01-01  37.9   0.000      57.4       10.0
1     2014-01-02  35.9   0.161      82.0       11.3
2     2014-01-03  22.4   0.015      54.1       30.5
3     2014-01-04  25.4   0.000      52.6       13.3
4     2014-01-05  37.1   0.041      78.7       11.0
5     2014-01-06  36.6   0.107      63.7       24.9
6     2014-01-07  12.9   0.005      33.3       18.5
7     2014-01-08  22.2   0.000      40.4        7.8
8     2014-01-09  33.2   0.000      55.8        8.1
9     2014-01-10  34.7   0.339      83.7        6.6
10    2014-01-11  45.6   0.425      88.8       14.6
11    2014-01-12  47.3   0.001      53.1       16.6
12    2014-01-13  45.1   0.003      65.1       14.6
13    2014-01-14  48.5   0.623      80.4       14.7
14    2014-01-15  42.4   0.002      81.0       21.2
15    2014-01-16  37.3   0.000      52.7       15.2
16    2014-01-17  38.8   0.002      63.9       11.0
17    2014-01-18  31.7   0.000      50.3       18.4
18    2014-01-19  36.8   0.000      46.0       16.9
19    2014-01-20  45.5   0.000      46.7       17.8
20    2014-01-21  30.5   0.072      70.2       24.2
21    2014-01-22  14.2   0.000      44.1       27.0
22    2014-01-23  18.7   0.000      44.2       16.8
23    2014-01-24  17.6   0.000      38.7       17.5
24    2014-01-25  27.7   0.000      41.7       22.9
25    2014-01-26  28.6   0.000      44.1       17.6
26    2014-01-27  36.5   0.000      45.7       25.4
27    2014-01-28  17.4   0.000      35.2       21.7
28    2014-01-29  19.0   0.011      43.4       18.1
29    2014-01-30  24.0   0.000      41.8        9.0
30    2014-01-31  35.2   0.000      41.8        8.8
31    2014-02-01  39.9   0.000      51.1       10.2
32    2014-02-02  47.1   0.000      52.4        9.1
33    2014-02-03  39.9   1.371      80.4       16.4
34    2014-02-04  33.8   0.019      63.5        9.9
35    2014-02-05  36.3   0.364      79.8       29.0
36    2014-02-06  33.3   0.000      48.3       19.0
37    2014-02-07  35.7   0.000      49.9       10.7
38    2014-02-08  31.9   0.000      46.3        9.6
39    2014-02-09  32.1   0.000      64.3        9.9
40    2014-02-10  30.2   0.000      49.8       16.8
41    2014-02-11  26.8   0.000      44.2       13.6
42    2014-02-12  24.9   0.058      55.3       13.5
43    2014-02-13  34.3   1.563      83.5       23.2
44    2014-02-14  41.6   0.044      51.8       19.6
45    2014-02-15  36.2   0.099      64.3       24.1
46    2014-02-16  32.2   0.000      46.6       16.1
47    2014-02-17  30.4   0.000      46.0       13.7
48    2014-02-18  40.2   0.048      60.5       15.7
49    2014-02-19  47.8   0.094      62.2       16.2
50    2014-02-20  46.4   0.000      55.7       10.6
51    2014-02-21  49.5   0.031      75.2       19.0
52    2014-02-22  47.0   0.000      59.0       15.8
53    2014-02-23  52.2   0.000      42.9       15.8
54    2014-02-24  41.7   0.003      38.0       24.2
55    2014-02-25  33.8   0.108      55.0        9.6
56    2014-02-26  32.0   0.072      52.9       19.0
57    2014-02-27  31.3   0.000      39.7       27.7
58    2014-02-28  21.9   0.000      30.8       23.1
59    2014-03-01  33.6   0.000      43.7        9.9
60    2014-03-02  42.0   0.154      65.5       13.4
61    2014-03-03  24.7   0.549      67.0       25.1
62    2014-03-04  23.0   0.000      43.7       14.2
63    2014-03-05  33.8   0.000      48.2       16.4
64    2014-03-06  31.4   0.000      52.4       17.8
65    2014-03-07  37.6   0.000      61.7       15.6
66    2014-03-08  47.3   0.000      54.9       10.8
67    2014-03-09  47.2   0.000      43.9       18.9
68    2014-03-10  47.7   0.000      47.2       19.9
69    2014-03-11  55.0   0.000      49.4        8.8
70    2014-03-12  53.6   0.208      62.9       26.3
71    2014-03-13  30.7   0.302      32.5       29.6
72    2014-03-14  42.9   0.000      33.5       20.0
73    2014-03-15  57.7   0.000      27.8       19.4
74    2014-03-16  42.2   0.127      51.5       16.7
75    2014-03-17  29.0   0.480      75.3       17.7
76    2014-03-18  37.0   0.000      54.9       14.7
77    2014-03-19  40.1   0.344      78.3        9.6
78    2014-03-20  50.6   0.016      56.3       20.8
79    2014-03-21  49.1   0.000      50.6       13.6
80    2014-03-22  55.0   0.000      50.0       14.7
81    2014-03-23  45.2   0.000      43.2       20.1
82    2014-03-24  33.9   0.000      33.6       20.8
83    2014-03-25  34.0   0.264      73.9       12.1
84    2014-03-26  33.7   0.024      47.6       26.7
85    2014-03-27  39.0   0.000      38.9       14.9
86    2014-03-28  55.8   0.047      62.1       22.7
87    2014-03-29  58.2   0.992      88.1       11.3
88    2014-03-30  45.0   1.062      82.5       25.7
89    2014-03-31  53.8   0.002      43.3       20.5
90    2014-04-01  53.6   0.000      47.0       10.4
91    2014-04-02  54.3   0.000      63.2        7.5
92    2014-04-03  59.3   0.000      60.3       11.1
93    2014-04-04  54.9   0.000      67.5       15.4
94    2014-04-05  53.1   0.059      54.2       20.3
95    2014-04-06  49.5   0.000      35.8       13.4
96    2014-04-07  48.4   0.383      75.2       12.1
97    2014-04-08  58.3   0.041      65.2       20.5
98    2014-04-09  56.8   0.004      45.2       20.7
99    2014-04-10  59.3   0.000      41.3       21.2
100   2014-04-11  68.0   0.000      41.0       19.2
101   2014-04-12  66.6   0.000      49.2       12.6
102   2014-04-13  69.6   0.000      57.8       18.1
103   2014-04-14  71.8   0.000      56.0       25.5
104   2014-04-15  58.4   1.555      80.0       24.4
105   2014-04-16  41.7   0.001      38.5       27.0
106   2014-04-17  46.4   0.000      53.4       14.6
107   2014-04-18  46.6   0.000      58.5        8.7
108   2014-04-19  57.1   0.000      49.0       10.1
109   2014-04-20  56.2   0.000      47.9       13.8
110   2014-04-21  55.6   0.000      46.6        8.9
111   2014-04-22  61.0   0.036      68.2       11.2
112   2014-04-23  56.0   0.000      45.3       23.7
113   2014-04-24  54.8   0.000      33.4       15.9
114   2014-04-25  57.3   0.393      55.5       18.0
115   2014-04-26  63.7   0.020      52.6       18.8
116   2014-04-27  59.6   0.000      40.2       18.6
117   2014-04-28  55.5   0.121      59.6       11.1
118   2014-04-29  50.5   1.143      85.6       15.7
119   2014-04-30  57.8   2.716      90.7       14.1
120   2014-05-01  67.5   0.158      69.6       15.9
121   2014-05-02  63.7   0.001      40.6       16.4
122   2014-05-03  64.9   0.000      45.5       13.6
123   2014-05-04  65.2   0.000      44.3       24.8
124   2014-05-05  57.4   0.358      45.4       15.9
125   2014-05-06  61.3   0.017      61.7       13.2
126   2014-05-07  59.4   0.138      66.0        8.9
127   2014-05-08  68.4   0.000      71.3        7.6
128   2014-05-09  67.5   0.000      78.3        9.7
129   2014-05-10  71.1   0.083      74.0       17.1
130   2014-05-11  71.0   0.000      58.5       11.5
131   2014-05-12  73.1   0.072      69.7       13.5
132   2014-05-13  76.6   0.000      70.9       12.5
133   2014-05-14  63.6   0.000      86.4       13.7
134   2014-05-15  72.2   0.186      80.3       18.0
135   2014-05-16  65.2   1.892      71.6       21.6
136   2014-05-17  60.9   0.000      50.3       14.5
137   2014-05-18  60.7   0.000      44.1       15.1
138   2014-05-19  62.5   0.000      43.9        9.8
139   2014-05-20  66.1   0.000      50.9       11.8
140   2014-05-21  69.4   0.164      68.4        8.8
141   2014-05-22  76.3   0.003      62.6       15.6
142   2014-05-23  70.9   0.000      43.3       20.5
143   2014-05-24  67.6   0.000      50.0       13.5
144   2014-05-25  72.3   0.000      48.3       10.0
145   2014-05-26  74.9   0.000      58.1       12.3
146   2014-05-27  77.2   0.557      68.4       13.4
147   2014-05-28  76.1   0.366      69.9       17.6
148   2014-05-29  59.6   0.313      84.9       11.0
149   2014-05-30  65.8   0.002      70.4       10.9
150   2014-05-31  71.3   0.000      49.1       13.9
151   2014-06-01  67.8   0.000      60.2       12.1
152   2014-06-02  70.2   0.000      57.2       14.3
153   2014-06-03  76.1   0.013      65.0        9.8
154   2014-06-04  79.0   0.335      61.1       12.2
155   2014-06-05  73.2   0.072      63.9       19.1
156   2014-06-06  71.7   0.000      47.6       14.1
157   2014-06-07  74.8   0.000      53.0       10.6
158   2014-06-08  75.8   0.007      61.7       14.5
159   2014-06-09  77.2   0.411      73.0       10.2
160   2014-06-10  79.4   0.698      74.9       10.3
161   2014-06-11  77.8   0.746      76.6       14.7
162   2014-06-12  74.8   0.098      82.2       12.6
163   2014-06-13  75.7   0.202      77.5       15.5
164   2014-06-14  72.3   0.008      54.9       19.0
165   2014-06-15  72.0   0.000      55.1       10.6
166   2014-06-16  79.2   0.000      62.3       10.1
167   2014-06-17  83.6   0.000      62.2       12.1
168   2014-06-18  87.0   0.000      56.3       17.1
169   2014-06-19  79.7   0.006      66.9       14.6
170   2014-06-20  76.8   0.000      52.4        9.8
171   2014-06-21  72.0   0.022      63.5       10.9
172   2014-06-22  74.2   0.085      65.9        8.8
173   2014-06-23  76.1   0.000      60.1       13.6
174   2014-06-24  77.4   0.000      63.8       13.6
175   2014-06-25  81.2   0.455      71.8       13.6
176   2014-06-26  81.6   0.000      59.3       17.0
177   2014-06-27  79.6   0.004      61.0       13.4
178   2014-06-28  77.5   0.000      54.4       13.2
179   2014-06-29  77.7   0.000      50.0       12.4
180   2014-06-30  79.6   0.000      59.7       12.4
181   2014-07-01  83.6   0.001      63.0       17.7
182   2014-07-02  86.2   0.010      62.6       15.6
183   2014-07-03  79.7   0.326      76.0       15.5
184   2014-07-04  76.3   0.195      57.6       23.4
185   2014-07-05  74.5   0.000      40.6       14.6
186   2014-07-06  77.3   0.000      50.4       15.0
187   2014-07-07  83.5   0.000      50.3       17.2
188   2014-07-08  83.8   0.633      56.1       23.2
189   2014-07-09  77.5   0.100      75.4       13.4
190   2014-07-10  77.3   0.620      72.2       10.0
191   2014-07-11  78.2   0.000      65.9        7.9
192   2014-07-12  81.0   0.000      65.8       13.9
193   2014-07-13  82.9   0.046      65.3       20.4
194   2014-07-14  81.6   0.154      72.1       29.6
195   2014-07-15  78.8   1.762      77.5       16.6
196   2014-07-16  76.2   0.006      55.9       13.5
197   2014-07-17  75.5   0.000      47.1       11.0
198   2014-07-18  76.4   0.000      48.7        8.7
199   2014-07-19  77.1   0.000      52.3       10.2
200   2014-07-20  76.9   0.000      66.6        8.7
201   2014-07-21  77.7   0.000      66.1       10.0
202   2014-07-22  79.5   0.000      68.9       11.2
203   2014-07-23  83.4   0.006      65.0       13.5
204   2014-07-24  77.5   0.013      62.7       13.1
205   2014-07-25  75.0   0.000      50.7       13.4
206   2014-07-26  78.8   0.000      62.3       10.9
207   2014-07-27  79.3   0.072      72.4       17.5
208   2014-07-28  79.9   0.028      57.5       21.8
209   2014-07-29  71.0   0.000      49.8       16.9
210   2014-07-30  71.1   0.000      51.5       12.2
211   2014-07-31  77.1   0.000      58.7       12.5
212   2014-08-01  76.6   0.001      67.7       13.2
213   2014-08-02  74.5   0.175      69.3        9.1
214   2014-08-03  77.6   0.000      70.6       12.4
215   2014-08-04  77.8   0.409      66.0        7.9
216   2014-08-05  81.3   0.000      58.9        8.8
217   2014-08-06  77.7   0.375      63.5       24.2
218   2014-08-07  78.1   0.000      55.7       13.5
219   2014-08-08  75.8   0.000      53.6        8.8
220   2014-08-09  77.1   0.017      63.0       14.5
221   2014-08-10  78.9   0.000      60.6        9.0
222   2014-08-11  75.8   0.031      64.0       12.6
223   2014-08-12  74.7   1.778      81.5       14.5
224   2014-08-13  78.2   0.000      59.2       20.2
225   2014-08-14  74.6   0.000      48.6       15.6
226   2014-08-15  72.5   0.000      45.1       12.6
227   2014-08-16  75.0   0.000      47.6        9.8
228   2014-08-17  78.7   0.006      61.0       11.4
229   2014-08-18  77.9   0.000      59.8        9.6
230   2014-08-19  78.0   0.001      68.2        9.9
231   2014-08-20  77.3   0.240      65.0       13.4
232   2014-08-21  77.9   0.026      72.6       10.1
233   2014-08-22  77.8   0.001      73.3        9.9
234   2014-08-23  73.2   0.217      77.3       10.9
235   2014-08-24  74.2   0.000      63.0       11.0
236   2014-08-25  74.9   0.001      59.9       12.3
237   2014-08-26  77.3   0.000      59.2        7.8
238   2014-08-27  79.1   0.000      63.2       10.1
239   2014-08-28  79.8   0.000      54.2       14.6
240   2014-08-29  73.0   0.000      49.5        9.8
241   2014-08-30  76.6   0.000      67.6        9.9
242   2014-08-31  82.6   0.308      69.8       16.8
243   2014-09-01  81.9   0.020      74.2       10.0
244   2014-09-02  84.2   0.092      66.8       12.5
245   2014-09-03  81.1   0.000      64.1        8.6
246   2014-09-04  80.7   0.000      65.0       10.3
247   2014-09-05  82.9   0.000      70.1       13.2
248   2014-09-06  83.0   0.142      69.4       19.9
249   2014-09-07  75.8   0.009      56.2       16.5
250   2014-09-08  72.5   0.000      61.7       15.2
251   2014-09-09  73.3   0.000      70.0       12.4
252   2014-09-10  74.7   0.000      67.0        9.9
253   2014-09-11  79.9   0.005      65.1       14.5
254   2014-09-12  73.1   0.000      55.6       18.8
255   2014-09-13  68.1   0.179      67.9       15.4
256   2014-09-14  64.5   0.062      57.2       11.0
257   2014-09-15  67.1   0.000      61.5       11.0
258   2014-09-16  71.5   0.000      58.6       16.7
259   2014-09-17  67.7   0.000      56.1        9.7
260   2014-09-18  70.1   0.000      62.1       13.3
261   2014-09-19  68.5   0.000      65.4       10.9
262   2014-09-20  72.1   0.000      65.4        9.8
263   2014-09-21  73.9   0.000      65.4       12.7
264   2014-09-22  69.9   0.000      42.5       21.3
265   2014-09-23  62.9   0.000      49.4       10.2
266   2014-09-24  65.1   0.064      67.1       16.7
267   2014-09-25  65.4   0.622      81.4       17.8
268   2014-09-26  68.6   0.000      65.0       11.3
269   2014-09-27  70.4   0.000      60.1        6.8
270   2014-09-28  70.5   0.000      65.9        9.7
271   2014-09-29  69.0   0.000      77.1       10.6
272   2014-09-30  70.3   0.000      75.2       10.0
273   2014-10-01  69.6   0.049      73.9        9.7
274   2014-10-02  68.2   0.000      71.1        9.2
275   2014-10-03  68.1   0.054      75.0       13.6
276   2014-10-04  65.5   0.092      57.4       22.7
277   2014-10-05  54.5   0.000      50.1       11.4
278   2014-10-06  62.7   0.000      53.2       19.1
279   2014-10-07  66.6   0.158      62.8       16.0
280   2014-10-08  69.2   0.001      56.1       17.1
281   2014-10-09  65.4   0.000      48.6       12.2
282   2014-10-10  62.1   0.047      63.1       10.8
283   2014-10-11  56.9   0.395      82.8       12.0
284   2014-10-12  58.8   0.000      65.4        8.7
285   2014-10-13  64.1   0.097      80.6        5.7
286   2014-10-14  72.9   0.000      76.0       22.3
287   2014-10-15  72.5   1.403      78.8       17.7
288   2014-10-16  62.6   0.000      79.7       10.8
289   2014-10-17  64.7   0.018      66.6       14.7
290   2014-10-18  62.8   0.003      57.4       20.6
291   2014-10-19  55.6   0.000      44.6       19.3
292   2014-10-20  56.6   0.000      59.6       15.9
293   2014-10-21  60.3   0.147      67.2       12.8
294   2014-10-22  56.0   0.947      77.9       20.4
295   2014-10-23  59.8   0.000      53.5       23.8
296   2014-10-24  61.9   0.000      44.7       18.3
297   2014-10-25  60.4   0.000      51.7       13.4
298   2014-10-26  63.9   0.000      35.0       21.6
299   2014-10-27  57.4   0.000      50.6       10.1
300   2014-10-28  66.1   0.000      55.8       12.7
301   2014-10-29  62.4   0.030      71.3       20.3
302   2014-10-30  54.7   0.000      58.5       14.6
303   2014-10-31  51.6   0.000      56.1        8.8
304   2014-11-01  51.6   0.001      58.3       24.3
305   2014-11-02  48.1   0.021      40.2       32.9
306   2014-11-03  52.9   0.000      31.6       14.7
307   2014-11-04  57.1   0.000      48.2        9.5
308   2014-11-05  59.5   0.000      55.6        8.8
309   2014-11-06  58.1   0.518      76.0       13.1
310   2014-11-07  51.9   0.008      47.2       21.6
311   2014-11-08  45.1   0.000      50.1       13.6
312   2014-11-09  51.5   0.000      56.9        9.1
313   2014-11-10  52.2   0.000      63.9       10.3
314   2014-11-11  57.1   0.000      74.3        9.1
315   2014-11-12  60.0   0.001      60.0       23.2
316   2014-11-13  43.7   0.032      55.1       13.7
317   2014-11-14  39.0   0.000      45.7       20.3
318   2014-11-15  38.2   0.000      44.1       13.9
319   2014-11-16  43.0   0.012      51.5       12.3
320   2014-11-17  46.4   0.706      73.9       18.7
321   2014-11-18  31.7   0.005      32.6       24.8
322   2014-11-19  31.2   0.000      36.9       17.9
323   2014-11-20  43.5   0.000      35.6       20.4
324   2014-11-21  34.7   0.000      32.7       25.4
325   2014-11-22  38.2   0.000      46.5       15.4
326   2014-11-23  48.9   0.036      47.5       10.9
327   2014-11-24  65.5   0.275      70.0       20.4
328   2014-11-25  56.5   0.000      53.3       16.6
329   2014-11-26  42.0   1.076      78.6       16.5
330   2014-11-27  41.4   0.000      65.4       13.7
331   2014-11-28  37.0   0.000      49.4       13.9
332   2014-11-29  41.2   0.000      51.1       13.3
333   2014-11-30  52.0   0.000      55.2       13.6
334   2014-12-01  57.2   0.234      63.3       20.3
335   2014-12-02  39.5   0.557      78.0       14.1
336   2014-12-03  46.6   0.068      75.6       17.9
337   2014-12-04  42.8   0.001      52.4        8.8
338   2014-12-05  42.8   0.014      67.7        5.7
339   2014-12-06  47.5   0.452      81.1       21.2
340   2014-12-07  43.0   0.023      49.0       24.2
341   2014-12-08  36.2   0.000      55.6       14.4
342   2014-12-09  40.3   0.336      79.1       15.7
343   2014-12-10  45.0   0.031      54.2       25.7
344   2014-12-11  40.6   0.000      39.0       17.0
345   2014-12-12  41.9   0.000      41.7       17.8
346   2014-12-13  39.9   0.000      58.3       14.3
347   2014-12-14  45.4   0.000      61.5       14.5
348   2014-12-15  47.5   0.000      69.5        7.6
349   2014-12-16  45.0   0.397      82.3        7.9
350   2014-12-17  47.7   0.000      59.5       17.0
351   2014-12-18  39.4   0.000      46.7       18.0
352   2014-12-19  38.5   0.000      51.0       16.1
353   2014-12-20  35.6   0.000      54.0        7.8
354   2014-12-21  38.8   0.000      55.7        7.8
355   2014-12-22  36.3   0.248      73.9       12.2
356   2014-12-23  43.5   0.021      86.9        9.9
357   2014-12-24  49.9   0.897      89.2       10.0
358   2014-12-25  52.7   0.132      56.7       17.7
359   2014-12-26  43.7   0.000      62.8       12.2
360   2014-12-27  46.0   0.000      63.5        7.8
361   2014-12-28  52.1   0.057      65.2        9.1
362   2014-12-29  44.5   0.084      57.6       11.0
363   2014-12-30  39.4   0.000      44.6       13.4
364   2014-12-31  33.2   0.000      43.8       12.7
365   2015-01-01  36.1   0.000      45.2       14.5
366   2015-01-02  41.0   0.000      52.4        9.0
367   2015-01-03  39.0   0.482      77.6        6.7
368   2015-01-04  53.1   0.207      77.6       20.5
369   2015-01-05  40.0   0.000      33.9       22.3
370   2015-01-06  27.6   0.189      61.2        9.0
371   2015-01-07  23.9   0.001      46.7       23.2
372   2015-01-08  18.4   0.000      35.6       21.0
373   2015-01-09  32.0   0.000      33.7       22.3
374   2015-01-10  24.5   0.000      33.3       14.7
375   2015-01-11  31.1   0.000      48.9        9.1
376   2015-01-12  38.0   0.752      81.8        7.5
377   2015-01-13  34.8   0.000      52.1       19.1
378   2015-01-14  30.1   0.000      62.3       11.0
379   2015-01-15  34.7   0.000      61.8        9.8
380   2015-01-16  37.4   0.000      59.3       21.9
381   2015-01-17  33.5   0.000      49.0       14.9
382   2015-01-18  39.3   0.606      77.3       17.7